apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-nginx
spec: 
  selector:
    matchLabels:
      app: myapp-nginx
  replicas: 12
  template:
    metadata:
      labels:
        app: myapp-nginx
    spec:
      containers:
      - name: myapp
        image: nginx:latest
        ports: 
        - containerPort: 80
